#!/bin/bash

OPTION1="Connect to Listed Server"
OPTION2="Connect to Random Server"
OPTION3="Disconnect"
OPTION4="View the Server List"

OPTIONS="$OPTION1\n$OPTION2\n$OPTION3\n$OPTION4"


SELECTED="$(echo -e "$OPTIONS" | rofi -lines 5 -dmenu -p "VPNGate")"

case $SELECTED in
  $OPTION1)
    # connect to server in the list
    x-terminal-emulator -e bash -c "sudo vpngate connect; read line"
	;;
  $OPTION2)
    # connect to server a server selected randomly from the list
    x-terminal-emulator -e bash -c "sudo vpngate connect --random; read line"
	;;
  $OPTION3)
    # disconnect
    sudo killall openvpn
    ;;
  $OPTION4)
    # view server list
    x-terminal-emulator -e bash -c "vpngate list; read line"
    ;;
esac
